apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:jiH/36aq+1fMyIdXl2SgxYVtB/G52EcDBg/sHtSc81Pc3qGetr9k2Q==,iv:cZHFhUhlZ8McCHzJ5eB+AYUTwjQu9Qq8P07BY5Ed9Dg=,tag:1+gp3IUhfSDQr2BPj32eJg==,type:str]
sops:
  age:
    - recipient: age1yc2uu5yrjjnad3chvg02fvfx078vy0pq05fps5ygx68jekvlqe2swcf3yj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRGtiYTRaRGpJYmRQQ0lj
        Q0IxVXhHMmJqZkprZTlkVENObGlsMFhMYUNrCkhWZVZ2MU1pZlVuYnZtWlFwekJQ
        MVBOSVIrYXJjbDJkaC9FQXNCY3ZZVjQKLS0tIERPamNNamhXVEtMRE4rb2M3UUdu
        SWQxOVVzN2NxNUlkcUdLUEtheWRLME0KGtcXzjwvJMnIqKOBO3YfiKco8D+qtH2E
        uymCacGMd0TRU0Wzu5hTNozyTTn55BfE23GqS1LL5XqX0ZRjPUjIow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-30T13:20:34Z"
  mac: ENC[AES256_GCM,data:8rwRyViHSi4qBrREGjsBcWNZsbc6tcONq2ZfMVTKS/oWjEcXG65Lc1Mr+f0Ji5G47PV3nhfDU7h+z98iG4TBsDb3jzhG6ByOfXjYOIzs4Ku2d1E8z5CqfANcvWxBY7R/IGXHtPiJgw+2m+6ijYhcnZcV+8Z3hA7+/3lBdebAa4Y=,iv:45tuPoyL4pSl/y5Jgc8tircvhJO/2tKAcSvrKZ+cwrw=,tag:FBqq3LIyZ/pHWCf9F/zHTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
