apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:wBuoU7LIH2BX6Z3gNGXG,iv:9TE55pzlp+GXXHOsFi/q3PlDMXe7ofZ6E8AwhKFtcnY=,tag:L86L5psgiOZXpJdCPn+jRg==,type:str]
sops:
  age:
    - recipient: age1yc2uu5yrjjnad3chvg02fvfx078vy0pq05fps5ygx68jekvlqe2swcf3yj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZ1dQdHJsanJkSm5ENlVM
        VUJxaC9ZWVNBMzB6NEJpKy9rcG1pTjVpbHlVCkRrMlhORkpldnNiT0FRU3lZNmRn
        OTVQMXFmN0tIYmVUNGM2RndZa0czaUUKLS0tIGM1TXo2N0E4aTNHdGxZM0xKMzJu
        MHVlWkdVNXFndkp2TGFhWTlaQ0VBbkUKpJ575mXRc/b+EwRex638bmZeS8Aq2d33
        CzA+CtIeebytd6vCMOl86B5bhC9SXHMpGRJ1FXU8+qFFFTyIaORVYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-30T13:20:35Z"
  mac: ENC[AES256_GCM,data:sqiOF2q9z3Pjs+kl20VQ8WMnZcXg6plY2zpKtHwpODGWKs5xYc/Rv81nSfv3jttS0HCGUNL614Xn2UhKKbSYH7GhxpdbvIxF4thE97oLl1kKCQOKci9air1adMqzcy33WouK7K2XPSclmdOe1lvxYqNQo0hgUakLY1MZW0b5xaQ=,iv:+D+ShpIeAQVTI3so/2/Sza9ot/HvPAwdrAgh3/HJb/A=,tag:F4NzF0AsOeE7QF1JgtekDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
