apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:WAPO62y5Txmu5VOp0m9g99R15n4uWAv1yE91alwfDhk2BvLe/k2VA3M9nSCmWrm6N1PG61MyPAM/7IVpR6f8xQY7Tp29rjl1jSOXeMG3dpZaYeta7NVj/EcROFoiF56pPjiOsmFDO8T3FFO9unEb4OTD7+YfACaujNYDN8kW/PBIc9bsW7eG1s6axQTiChOAA1qq2PxjRCG1ALiz0ieRATuaTSRakYOufKU0FrPu1RIV3AUV,iv:H4CvuZs4hBSA0mvDlC8jzwJv4TxKdGlcBNx1lmQtwCQ=,tag:syqKz+i9xPh8TPnLYDUolw==,type:str]
sops:
  age:
    - recipient: age1yc2uu5yrjjnad3chvg02fvfx078vy0pq05fps5ygx68jekvlqe2swcf3yj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGd01wbE56aWpCcVFxWXB5
        WmlxRVBuR215YW1OSm45b3FjZ0R1R3h6T0V3CmVkOE82NGNPSHJ3bkY4bHM1dWhE
        U1Y3NDJyRE9NdlhIM2gyZHo1YnAySVEKLS0tIFRIZlh3bElKcUpVbmdma3JsUUVN
        QlpiclU5M3lCNXlqeEZ1K1JlUVBEVUEK9EKMX1VEvvfjYNLNVuSN08nqdQVIEqjk
        gcRJgRBtD06nRbuyGUtk90t9pQiByDUKwgTBdp8l2Q6nFPsidUBPww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-30T13:20:34Z"
  mac: ENC[AES256_GCM,data:9sw1z9n2hGu+dJlwn73f3ofcyhlzEmEhl7FA1ZXyIxuqzRfPigxki7eV61L4bw6fYUkDQwZhfXXfoFCXWa8EjWh0/D8jfAB4qVDZw/T2tkUjegQxdP5tQY4/gNVAMl7F6wSFJIMzlaVzW8HA9g+VluB2J23gBfT0c1aW6xUe+ps=,iv:Sws+8GiPe0Z9idJj8qirxjGWeKvBSwy3jHSV8X8L+qk=,tag:BPhtrzHnC8dOw1+o4EgIPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
