apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:gtsTN/wxfxowEZxGI8gUxEFKyTMd5rd+zz0OxOSBvKSM0GsfTQ5hEA==,iv:6ue+Rsr53UDrPf/Pm7VeYs0fe1TkgBGJv0AzXWvtWj4=,tag:4Jff8g7iWTWfat7C/9UTRw==,type:str]
sops:
  age:
    - recipient: age1yc2uu5yrjjnad3chvg02fvfx078vy0pq05fps5ygx68jekvlqe2swcf3yj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNzRwVnYzazVPcDI3c29u
        bEFJb1d1VDJTZjBUdTdpYnJhTDZ3U1pXTTBzClp5ekR5K2NVTXdPWGlXZCtjRjRr
        MDZmbWxtcEVxck1aNnNtb0V1bkVhOGcKLS0tIFdrWlRIcmZ0cldidkF1S0FWWjlx
        ME5tUmx1dWVBSE15NFFGb054NXRldTQKAdMT+OhULB8LWuO2dDjWQFF4dJ3OfL4g
        ixYxMYlfDoICQIEni7GhgtqxrxG+ohYpNMs1gvgSvu6v64VyMjakBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-30T13:20:34Z"
  mac: ENC[AES256_GCM,data:KwK7Cc2E/igBnT208wQbIRxE8wOx6+LDGRompc/7wQ0a4kCzVEfKEfmXcMaLIqtmlSSoUWP5c/gK8Bd4pszavF8LjTxHibI5Sd+ZFtIGQ7Z6qSd4zjpto5P4Q+1hBByABVmt7Cu5zugXe3jQPkmvQJ2T29KjlqA4JsyIa5OJrjk=,iv:pOoEaSJUJBUlj9xZWSFxlWbAyYKCDTaqX64j9WRsSwM=,tag:AOSJfwQLpfPoicTMgO7rYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
